# Generated by Django 5.0.2 on 2024-02-18 02:43

import django.db.models.deletion
import sgv.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('Nac', models.CharField(choices=[('VE', 'VENEZOLANO'), ('EX', 'EXTRANJERO')], default='VE', max_length=2, verbose_name='Nacionalidad')),
                ('Dni', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('First_name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('Last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Género')),
                ('photo', models.ImageField(default='Photo/defaul.jpg', upload_to=sgv.models.visitor_photo_upload_path, verbose_name='Fotografía')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='AccessSEDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateField(verbose_name='Fecha del Dia')),
                ('hours', models.TimeField(verbose_name='Hora de Entrada')),
                ('hoursEx', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('Automovils', models.CharField(choices=[('NONE', 'NO POSEE'), ('SEDANES', 'CARRO LIVIANO-(TIPO SEDAN)'), ('CARGA', 'CAMION')], default='NONE', max_length=8, verbose_name='tipo de Automovil')),
                ('Licenses', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa del Vehiculo')),
                ('obs', models.TextField(blank=True, max_length=140, null=True, verbose_name='Observaciones')),
                ('visitorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.visitors')),
            ],
            options={
                'verbose_name': 'Listado Accesos',
                'verbose_name_plural': 'Listado Accesos',
            },
        ),
    ]
