# Generated by Django 5.0.2 on 2024-02-18 22:56

import django.utils.timezone
import sgv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesssede',
            old_name='visitorID',
            new_name='visitor',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='update_at',
        ),
        migrations.AddField(
            model_name='visitors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitors',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='visitors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='photo',
            field=models.ImageField(default='Photo/default.jpg', upload_to=sgv.models.visitor_photo_upload_path, verbose_name='Fotografía'),
        ),
    ]
